# ─────────────────────────────
# LOCAL PROFILE (TESTING)
# ─────────────────────────────
spring:
  config:
    activate:
      on-profile: local

  data:
    mongodb:
      uri: mongodb://localhost:27017/interview

  mail:
    host: smtp.gmail.com
    port: 587
    username: testing991162@gmail.com
    password: ddgeczqkpxqamzut
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
